version: '3'
services:
  pmp:
    restart: always
    build:
      context: ./pmp-microservice
    ports:
      - '5001:5000'
    networks:
      - pmp-network

  couchserver:
    image: couchdb
    restart: always
    ports:
      - '5984:5984'
    networks:
      - pmp-network
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
networks:
  pmp-network:
    driver: bridge