from enum import Enum


class PMPLookupCodes(Enum):
    agreement_cancel_reasons = 'agreement-cancel-reasons'
    agreement_status = 'agreement-status'
    agreement_types = 'agreement-types'
    apa_action_types = 'apa-action-types'
    apa_macro_inputs = 'apa-macro-inputs'
    apa_macro_types = 'apa-macro-types'
    attribute_value_types = 'attribute-value-types'
    billing_producer_roles = 'billing-producer-roles'
    channels = 'channels'
    components = 'components'
    condition_logic_opers = 'condition-logic-opers'
    condition_logic_types = 'condition-logic-types'
    copy_clone_actions = 'copy-clone-actions'
    export_formats = 'export-formats'
    file_import_types = 'file-import-types'
    item_status = 'item-status'
    lead_follow = 'lead-follow'
    negotiation_status = 'negotiation-status'
    schedule_contents = 'schedule-contents'
    schedule_functions = 'schedule-functions'
    schedule_identity_types = 'schedule-identity-types'
    scheme_action_types = 'scheme-action-types'
    scheme_attachments = 'scheme-attachments'
    scheme_calc_value_types = 'scheme-calc-value-types'
    scheme_card_filters = 'scheme-card-filters'
    scheme_condition_types = 'scheme-condition-types'
    scheme_cost_types = 'scheme-cost-types'
    scheme_create_methods = 'scheme-create-methods'
    scheme_operator_types = 'scheme-operator-types'
    scheme_source_types = 'scheme-source-types'
    scheme_timeframes = 'scheme-timeframes'
    scheme_types = 'scheme-types'
    scheme_validation_types = 'scheme-validation-types'
    scheme_value_types = 'scheme-value-types'
    suspension_reasons = 'suspension-reasons'
    system_setting_types = 'system-setting-types'
    virtual_flavour_actions = 'virtual-flavour-actions'
    virtual_product_types = 'virtual-product-types'
